services:
  dialplan-service:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-dialplan-service:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiric_dialplan_service
    env_file:
      - ./.env
    networks:
      - sentiric-net
    restart: always