services:
  dialplan-service:
    image: ${DOCKER_REGISTRY:-ghcr.io/sentiric}/sentiric-dialplan-service:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sentiric_dialplan_service
    env_file:
      - ./.env
    # YENİ EKLENEN BÖLÜMLER:
    environment:
      # Go kodumuz DATABASE_URL bekliyor, .env'deki POSTGRES_URL'i ona atıyoruz.
      - DATABASE_URL=${POSTGRES_URL}
      # Go kodumuz GRPC_PORT bekliyor, .env'deki GRPC_PORT_DIALPLAN'ı ona atıyoruz.
      - GRPC_PORT=${GRPC_PORT_DIALPLAN}
    # depends_on:
    #   postgres:
    #     condition: service_healthy
    networks:
      - sentiric-net
    restart: always

networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge